# Generated by Django 2.2.4 on 2019-08-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'To do'), (1, 'Done')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
